require 'benchmark'

# Finds all distinct terms in the expression a^b given
# inclusive range [a, b] where a and b are both at least 2.
def distinct_terms(a:, b:)
  a = a.to_i
  b = b.to_i
  raise ArgumentError, 'Argument is not numeric' unless a.is_a? Integer and b.is_a? Integer
  ar = []
  (2..a).each do |i|
  (2..b).each do |j|
      ar << i ** j
    end
  end
  ar.uniq
end

time = Benchmark.measure do
  puts 'The cardinality of the distinct terms generated by a^b '\
  "for a in [2, 100] and b in [2, 100] is #{distinct_terms(a: 100, b: 100).length}"
end
puts "Time elapsed (in seconds): #{time}"